import { Metadata } from "next";
import { ContentTypeTabs } from "./_components/content-type-tabs";

export const metadata: Metadata = {
  title: "Verify Content",
  description: "Upload an image, audio file, video, or paste text to check if it was generated by AI. Get trust scores and model fingerprinting.",
};

export default function VerifyPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="mx-auto max-w-3xl text-center mb-10">
        <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
          Verify Any Content
        </h1>
        <p className="mt-3 text-muted-foreground">
          Upload or paste content to check if it was generated by AI. Get detailed trust scores and model fingerprinting.
        </p>
      </div>
      <div className="mx-auto max-w-3xl">
        <ContentTypeTabs />
      </div>
    </div>
  );
}
